from dotenv import load_dotenv
import os

load_dotenv()

AZURE_OPENAI_ENDPOINT = os.getenv("AZURE_OPENAI_ENDPOINT")
AZURE_OPENAI_DEPLOYMENT = os.getenv("AZURE_OPENAI_DEPLOYMENT")
AZURE_OPENAI_API_KEY = os.getenv("AZURE_OPENAI_API_KEY")

AZURE_AI_SEARCH_ENDPOINT = os.getenv("AZURE_AI_SEARCH_ENDPOINT")
AZURE_AI_SEARCH_KEY = os.getenv("AZURE_AI_SEARCH_KEY")

FOUNDRY_PROJECT_ENDPOINT = os.getenv("FOUNDRY_PROJECT_ENDPOINT")
FOUNDRY_MODEL_DEPLOYMENT = os.getenv("FOUNDRY_MODEL_DEPLOYMENT")
FOUNDRY_AGENT_NAME = os.getenv("FOUNDRY_AGENT_NAME")

FOUNDRY_PROJECT_ENDPOINT_CONTOSO = os.getenv("FOUNDRY_PROJECT_ENDPOINT_CONTOSO")
FOUNDRY_AGENT_NAME_CONTOSO = os.getenv("FOUNDRY_AGENT_NAME_CONTOSO")
FOUNDRY_KNOWLEDGEBASE_CONTOSO = os.getenv("FOUNDRY_KNOWLEDGEBASE_CONTOSO")

# Lab 07 - Multi-Agent
FOUNDRY_PROJECT_ENDPOINT_MULTI = os.getenv("FOUNDRY_PROJECT_ENDPOINT_MULTI")
FOUNDRY_MODEL_DEPLOYMENT_MULTI = os.getenv("FOUNDRY_MODEL_DEPLOYMENT_MULTI")
FOUNDRY_AGENT_NAME_MULTI = os.getenv("FOUNDRY_AGENT_NAME_MULTI")

required = {
    "AZURE_OPENAI_ENDPOINT": AZURE_OPENAI_ENDPOINT,
    "AZURE_OPENAI_DEPLOYMENT": AZURE_OPENAI_DEPLOYMENT,
    "AZURE_OPENAI_API_KEY": AZURE_OPENAI_API_KEY,
    "FOUNDRY_PROJECT_ENDPOINT": FOUNDRY_PROJECT_ENDPOINT,
    "FOUNDRY_MODEL_DEPLOYMENT": FOUNDRY_MODEL_DEPLOYMENT,
    "FOUNDRY_AGENT_NAME": FOUNDRY_AGENT_NAME,
    "FOUNDRY_PROJECT_ENDPOINT_MULTI": FOUNDRY_PROJECT_ENDPOINT_MULTI,
    "FOUNDRY_MODEL_DEPLOYMENT_MULTI": FOUNDRY_MODEL_DEPLOYMENT_MULTI,
    "FOUNDRY_AGENT_NAME_MULTI": FOUNDRY_AGENT_NAME_MULTI

}

for name, value in required.items():
    if not value:
        raise ValueError(f"{name} ontbreekt")